export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_SUCCESS = "BOOKS_SUCCESS";
export const BOOKS_FAILURE = "BOOKS_FAILURE";

export const BOOKS_ADD_REQUEST = "BOOKS_ADD_REQUEST";
export const BOOKS_ADD_SUCCESS = "BOOKS_ADD_SUCCESS";
export const BOOKS_ADD_FAILURE = "BOOKS_ADD_FAILURE";

export const BOOKS_DELETE = "BOOKS_DELETE";
export const BOOKS_SORT = "BOOKS_SORT";
